version: '3'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: 'database'
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_BASICAUTH_USR:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_BASICAUTH_PWD:-adminpassword}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USR:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PWD:-rootpassword}
    restart: always
    networks:
      - mongo-network

  database:
    image: mongo
    container_name: mongo-server
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USR:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PWD:-rootpassword}
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - mongo-network
    restart: always

networks: 
    mongo-network:
      driver: bridge